<a href="https://colab.research.google.com/github/KseniyaKanushina/homework_DS_2022/blob/main/NLP2_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Классная** **работа** **2**

In [ ]:
#Установка нужных пакетов
!pip install --upgrade nltk gensim bokeh umap-learn

import itertools
import string

import numpy as np
import umap

from matplotlib import pyplot as plt

from IPython.display import clear_output
from string import punctuation

import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import WordPunctTokenizer
from sklearn.feature_extraction.text import (CountVectorizer, TfidfTransformer,
                                             TfidfVectorizer)

In [31]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

File ‘./quora.txt’ already there; not retrieving.


In [32]:
data = list(open("./quora.txt", encoding="utf-8"))
data[50]

"What TV shows or books help you read people's body language?\n"

In [33]:
tokenizer = WordPunctTokenizer()

print(tokenizer.tokenize(data[0]))

['Can', 'I', 'get', 'back', 'with', 'my', 'ex', 'even', 'though', 'she', 'is', 'pregnant', 'with', 'another', 'guy', "'", 's', 'baby', '?']


# Задание 10: Реализовать Bag of words на data_tok (можно на NLTK, можно без)

In [34]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [35]:
def vectorize(tokens):
    ''' This function takes list of words in a sentence as input
    and returns a vector of size of filtered_vocab.It puts 0 if the
    word is not present in tokens and count of token if present.'''
    vector = []
    for w in filtered_vocab:
        vector.append(tokens.count(w))
    return vector


def unique(sequence):
    '''This functions returns a list in which the order remains
    same and no item repeats.Using the set() function does not
    preserve the original ordering,so i didnt use that instead'''
    seen = set()
    return [x for x in sequence if not (x in seen or seen.add(x))]


In [36]:
with open('./quora.txt', encoding='utf-8') as f:
    data = list(f)

tokenizer = WordPunctTokenizer()
data_tok = [tokenizer.tokenize(row.lower()) for row in data]

In [38]:
sub_data_tok = data_tok[:50]

pre_dict = []
for s in sub_data_tok:
    pre_dict.extend(s)
vocab = unique(pre_dict)

filtered_vocab = []
for w in vocab:
    if w not in stopwords.words('english') and w not in punctuation:
        filtered_vocab.append(w)

vectors = [vectorize(s) for s in sub_data_tok]

data_len = len(sub_data_tok)
cosines = {}
for i in range(data_len):
    for j in range(i + 1, data_len):
        cosines[i, j] = (np.dot(vectors[i], vectors[j]) /
                         np.linalg.norm(vectors[i]) / np.linalg.norm(vectors[j]))
max(cosines.values())
closest_pair = max(cosines, key=cosines.get)
for x in closest_pair:
    print(sub_data_tok[x])


['what', 'is', 'your', 'review', 'of', 'osquery', '?']
['what', 'is', 'your', 'review', 'of', 'ipad', 'mini', '2', '?']


In [1]:
# https://www.kaggle.com/prateekmaj21/tf-idf-in-python

In [2]:
text=["kolkata big city india trade","mumbai financial capital india","delhi capital india","kolkata capital colonial times",
     "bangalore tech hub india software","mumbai hub trade commerce stock exchange","kolkata victoria memorial","delhi india gate",
      "mumbai gate way india trade business","delhi red fort india","kolkata metro oldest india",
      "delhi metro largest metro network india"]


In [3]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
#using the count vectorizer
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)

  (0, 14)	1
  (0, 1)	1
  (0, 4)	1
  (0, 13)	1
  (0, 26)	1
  (1, 13)	1
  (1, 18)	1
  (1, 9)	1
  (1, 3)	1
  (2, 13)	1
  (2, 3)	1
  (2, 7)	1
  (3, 14)	1
  (3, 3)	1
  (3, 5)	1
  (3, 25)	1
  (4, 13)	1
  (4, 0)	1
  (4, 24)	1
  (4, 12)	1
  (4, 22)	1
  (5, 26)	1
  (5, 18)	1
  (5, 12)	1
  (5, 6)	1
  :	:
  (6, 14)	1
  (6, 27)	1
  (6, 16)	1
  (7, 13)	1
  (7, 7)	1
  (7, 11)	1
  (8, 13)	1
  (8, 26)	1
  (8, 18)	1
  (8, 11)	1
  (8, 28)	1
  (8, 2)	1
  (9, 13)	1
  (9, 7)	1
  (9, 21)	1
  (9, 10)	1
  (10, 14)	1
  (10, 13)	1
  (10, 17)	1
  (10, 20)	1
  (11, 13)	1
  (11, 7)	1
  (11, 17)	2
  (11, 15)	1
  (11, 19)	1


In [5]:
print(word_count.toarray())

[[0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 2 0 1 0 0 0 0 0 0 0 0 0]]


In [6]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [7]:
#inverse document frequency
df_idf.sort_values(by=['idf_weights'])

idf_weights
india         1.262364
kolkata       1.955511
delhi         1.955511
trade         2.178655
capital       2.178655
mumbai        2.178655
gate          2.466337
hub           2.466337
metro         2.466337
times         2.871802
tech          2.871802
stock         2.871802
software      2.871802
red           2.871802
oldest        2.871802
network       2.871802
bangalore     2.871802
largest       2.871802
victoria      2.871802
fort          2.871802
financial     2.871802
exchange      2.871802
commerce      2.871802
colonial      2.871802
city          2.871802
business      2.871802
big           2.871802
memorial      2.871802
way           2.871802

In [8]:
#tfidf
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
financial  0.653123
capital    0.495483
mumbai     0.495483
india      0.287095
bangalore  0.000000
memorial   0.000000
victoria   0.000000
trade      0.000000
times      0.000000
tech       0.000000
stock      0.000000
software   0.000000
red        0.000000
oldest     0.000000
network    0.000000
metro      0.000000
kolkata    0.000000
largest    0.000000
big        0.000000
hub        0.000000
gate       0.000000
fort       0.000000
exchange   0.000000
delhi      0.000000
commerce   0.000000
colonial   0.000000
city       0.000000
business   0.000000
way        0.000000

Задание 1. Реализовать tfidf датасета 

In [ ]:
# выгружаем датасет:
!wget https://www.dropbox.com/s/obaitrix9jyu84r/quora.txt?dl=1 -O ./quora.txt -nc

In [12]:
data = list(open("./quora.txt", encoding="utf-8"))
text = data[:50]

In [13]:
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)

  (0, 37)	1
  (0, 101)	1
  (0, 26)	1
  (0, 265)	2
  (0, 161)	1
  (0, 82)	1
  (0, 80)	1
  (0, 233)	1
  (0, 210)	1
  (0, 131)	1
  (0, 190)	1
  (0, 12)	1
  (0, 110)	1
  (0, 25)	1
  (1, 257)	1
  (1, 14)	1
  (1, 218)	1
  (1, 252)	1
  (1, 236)	1
  (1, 182)	1
  (1, 88)	1
  (1, 93)	1
  (1, 6)	1
  (2, 261)	2
  (2, 256)	1
  :	:
  (47, 14)	1
  (47, 261)	1
  (47, 231)	1
  (47, 124)	1
  (47, 35)	1
  (47, 237)	1
  (47, 50)	1
  (47, 22)	1
  (48, 236)	1
  (48, 262)	1
  (48, 64)	1
  (48, 94)	1
  (48, 102)	1
  (48, 249)	1
  (48, 33)	1
  (48, 193)	1
  (49, 11)	1
  (49, 211)	1
  (49, 169)	1
  (49, 29)	1
  (49, 56)	1
  (49, 179)	1
  (49, 163)	1
  (49, 221)	1
  (49, 116)	1


In [14]:
print(word_count.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, index=count.get_feature_names(),columns=["idf_weights"])

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [16]:
df_idf.sort_values(by=['idf_weights'])

idf_weights
the         2.041454
is          2.159237
how         2.159237
what        2.223775
can         2.446919
...              ...
goldman     4.238678
graphic     4.238678
great       4.238678
guy         4.238678
zotac       4.238678

[274 rows x 1 columns]

In [17]:
tf_idf_vector=tfidf_transformer.transform(word_count)
feature_names = count.get_feature_names()
first_document_vector=tf_idf_vector[1]
df_tfifd= pd.DataFrame(first_document_vector.T.todense(), index=feature_names, columns=["tfidf"])
df_tfifd.sort_values(by=["tfidf"],ascending=False)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


tfidf
fast       0.375678
ways       0.375678
addiction  0.375678
some       0.375678
food       0.375678
...             ...
from       0.000000
george     0.000000
get        0.000000
girls      0.000000
zotac      0.000000

[274 rows x 1 columns]

In [39]:
data_len = len(sub_data_tok)
cosines = {}
for i in range(data_len):
    for j in range(i + 1, data_len):
        cosines[i, j] = (np.dot(vectors[i], vectors[j]) /
                         np.linalg.norm(vectors[i]) / np.linalg.norm(vectors[j]))
max(cosines.values())
closest_pair = max(cosines, key=cosines.get)
for x in closest_pair:
    print(sub_data_tok[x])

['what', 'is', 'your', 'review', 'of', 'osquery', '?']
['what', 'is', 'your', 'review', 'of', 'ipad', 'mini', '2', '?']
